### ISSUE TITLE
selfupdate function

### ISSUE THREAD

**Issue by sugarsweetrobotics** [tork-a/openrtm_tutorial#15]
菅です．

自己アップデートができればいいなと思って，fork先 (sugarsweetrobotics/openrtm_tutorial)では，USBのドライブ（僕はE:）に直接cloneしてgit pullすれば自己アップデートできるようにしてみました．PortableGitを入れて，gitのインストールも不要にしてみて，ルートにopenrtm_tutorialディレクトリができてしまうので，パスを変更して，ひととおりのデモが動くように直しました．

こういう変更はどうでしょう？というイシューです．

**Comment by 130s** [comment]
+1

(すみません，TORK の方針なんで英語で返しますが)

I was wondering the similar but your idea includes `PortableGit` so that `git` isn't necessary is better. 

If you can include `PortableGit` and open a pull request, I'm willing to review and merge.

**Comment by sugarsweetrobotics** [comment]
Okay, I'll do so

2014-04-04 15:44 GMT+09:00 Isaac Isao Saito notifications@github.com:

> +1
> 
> ($B$9$_$^$;$s!$(BTORK $B$NJ}?K$J$s$G1Q8l$GJV$7$^$9$,(B)
> 
> I was wondering the similar but your idea includes PortableGit so that gitisn't necessary is better.
> 
> If you can include PortableGit and open a pull request, I'm willing to
> review and merge.
> 
> $B!=(B
> Reply to this email directly or view it on GitHubhttps://github.com/tork-a/openrtm_tutorial/issues/15#issuecomment-39536146
> .

## 

///////////////////////////////////////////////////////////////////
// Yuki Suga, Ph.D.
// URL: http://www.ysuga.net/?lang=en
// E-mail: ysuga@ysuga.net
///////////////////////////////////////////////////////////////////

**Comment by 130s** [comment]
Added in https://github.com/tork-a/openrtm_tutorial/pull/16
