### ISSUE TITLE
Choreonoid not working?

### ISSUE THREAD

**Issue by 130s** [tork-a/openrtm_tutorial#27]
Waiting further input from @ysuga

**Comment by sugarsweetrobotics** [comment]
I inspected this bug.

Choreonoid uses CnoidRtc**.dll plugins that use OpenRTM-aist.

Followings are easy solutions:
1. Place runtimes (all dlls in OpenRTM-aist's runtime directory.) in the same folder of choreonoid.exe
2. set PATH environmental variables

1 is already tested. I recommend to do so.

**Comment by 130s** [comment]
Addressed by https://github.com/tork-a/openrtm_tutorial/pull/28 with the option 1 above. In the future someone can apply option 2, which is more ideal (option 1 is just as good for tutorial).
